version: "3.3"

services:
  website:
    container_name: gieu-website
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "${PORT:-8517}:${PORT:-8517}"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=${PORT:-8517}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8517}"]
      interval: 30s
      timeout: 10s
      retries: 3
