version: '2.4'

services:
  website:
    container_name: website
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
