version: "3.8"

services:
  website:
    container_name: gieu-website
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "${PORT:-4321}:${PORT:-4321}"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=${PORT:-4321}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-4321}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
