version: '2.4'

services:
  website:
    container_name: website
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}

      # - '8517:8517'
